### ISSUE TITLE
پیغام خطا در ثبت سرمایه برای صندوق نقش جهان 

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#10]
در صندوق نقش جهان که تازه ثبت کردم و حساب را مشخص کردم. ولی وقتی میرم در ثبت سرمایه و میخواهم سرمایه اشتراکی ثبت کنم ارور میدهد
![image](https://user-images.githubusercontent.com/24356465/86927794-02aeb980-c149-11ea-8f68-2d33b9f92e45.png)

**Comment by lamso1387** [comment]
درست شد
