### ISSUE TITLE
عدم نیاز به درج دیجیت (اعشار برای فیلدها)

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#11]
در بخش سود و زیان سرمایه گذاران، اعشار و دو رقم اعشار در سمت چپ قرار گرفته است که خوانش اعداد را مخدوش کرده است. به نظرم اعشار را حذف کن تا راحتتر خوانده شوند

**Comment by Hamedkalantari0111** [comment]
لطفا کلیه اعشارها رو بردار
در دو فیلد دیگر
سهم خالص سود به زیان بدون کارمزد و سود انتظاری بانکی هم اعشار است که خوانش را خراب کرده

**Comment by lamso1387** [comment]
انجام شد
