### ISSUE TITLE
عدم نمایش تمامی رکورد ها در بخش سود و زیان سرمایه گذاران در داشبورد

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#12]
در بخش سود و زیان سرمایه گذاران در داشبورد اسکرول کار میکنه ولی رکوردهای پایینی رو نمایش نمیده و اسکرول پایین نمیاد
![image](https://user-images.githubusercontent.com/24356465/87080270-a0cf7c00-c23c-11ea-9491-07438e5a0fb6.png)

**Comment by lamso1387** [comment]
برطرف شد
