### ISSUE TITLE
نیاز به پنجره یا ویزاد جدید در داشبورد برای نمایش سرمایه شخص به تفکیک صندوق

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#13]
نیاز به پنجره یا ویزاد جدید در داشبورد برای نمایش سرمایه شخص به تفکیک صندوق
یکی چنین چیزی نیاره

در فایل اکسل صفحه اول است. کافیه نام سرمایه گذار از لیست باکس انتخاب بشه و نشان بده هر شخص چه میزان سرمایه گذاری در هر صندوق کرده و ارزش سرمایه در هر صندوقش چقدر است؟
![image](https://user-images.githubusercontent.com/24356465/87080575-1dfaf100-c23d-11ea-8171-3dc344975505.png)

**Comment by Hamedkalantari0111** [comment]
نیاز به پنجره یا ویزاد جدید در داشبورد برای نمایش سرمایه شخص به تفکیک صندوق
یکی چنین چیزی نیاره

در فایل اکسل صفحه اول است. کافیه نام سرمایه گذار از لیست باکس انتخاب بشه و نشان بده هر شخص چه میزان سرمایه گذاری در هر صندوق کرده و ارزش سرمایه در هر صندوقش چقدر است؟
منظورم فقط یک جدولی از اون بالاست که از لیست باکس بخونه و اطلاعات رو نمایش بده
![image](https://user-images.githubusercontent.com/24356465/87080631-3bc85600-c23d-11ea-9bb3-60045db61913.png)

**Comment by Hamedkalantari0111** [comment]
فیدلهایی مه به عنوان سطر باید نمایش بده به صورت زیر است:
صندوق یک
صندوق دو
صندوق 3
...
کارمزد
جمع کل

**Comment by Hamedkalantari0111** [comment]
همچنینف دو تا ستون در جدول باشد
1- سرمایه گذاری
2- ازرش کنونی سرمایه

**Comment by Hamedkalantari0111** [comment]
در نهایت اگه خلاصه بگم یک چنین چیزی باید بشه:
![image](https://user-images.githubusercontent.com/24356465/87081168-18ea7180-c23e-11ea-829f-9a711d233c36.png)

**Comment by lamso1387** [comment]
شد
