### ISSUE TITLE
نمایش صندوق های دارای سرمایه در داشبورد

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#14]
در داشبورد فقط صندوق هایی رو نمایش بده که در آنها سرمایه وجود دارد. مثلا خاورمیانه دیگر پولی در آن نیست و نباید نمایش دهد
![image](https://user-images.githubusercontent.com/24356465/87082021-9498ee00-c23f-11ea-99ff-2f9c7114d67e.png)

**Comment by lamso1387** [comment]
ملاک کدام فیل باشد دقیقا؟
بنطرم در سرویس باشد ولی در اپ حذف شود موافقی؟

**Comment by Hamedkalantari0111** [comment]
بنظرم در هیچکدام نباشه. چون وقتی تو در هیچ صندوقی پولی نذاشتی، برای چی باید نمایشش بدی؟ اگر مثات من پنجاه تا صندوق ثبت کنم چرا باید همه رو نمایش بدم و مقدارش رو صفر بزنم؟
بنظرم وقتی موجود سرمایه گذاری صندوق صفر است، نباید در داشبورد نمایش داده شود

**Comment by lamso1387** [comment]
انجام شد
