### ISSUE TITLE
حذف سه فیلد آخر (سمت چپ) از جدول داشبورد

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#15]
در داشبورد، جدول بالا سه فیلد زیر را نمایش نده!
قیمت ابطال روز صندوق
تاریخ قیمت ابطال
تاریخ ابطال میلادی
![image](https://user-images.githubusercontent.com/24356465/87082328-11c46300-c240-11ea-851c-6ea3dba509be.png)

**Comment by lamso1387** [comment]
ایا در سرویس هم در خروجی نباشه؟
یا در سرویس باشه در اپ نباشه؟

اینطور فکر کن که ما الان 2 محصول داریم یکی سرویس یکی اپ که مستقل از هم هستن و هرکدوم میتونن مشتریای مجزا بدارن
مثلا یک چیزی میتونه تو سرویس باشه ولی تو اپ نباشه

**Comment by Hamedkalantari0111** [comment]
فقط فیلد تاریخ ابطال باشد در هر دو. دو فیلد دیگر را در سرویس و اپ حذف کن.
گس در نتیجه شد دو فیلد که باید حذف شود در سرویس اپ

**Comment by lamso1387** [comment]
انجام شد
