### ISSUE TITLE
مشکل در دکمه ویرایش!

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#17]
در زمانی که میخواهیم یکی از ثبت سرمایه ها رو ویرایش کنم، متاسفانه اطلاعات آن ردیف سرمایه به درستی نمایش داده نمی شود و باید اول آن ردیف سرمایه گذاری را حذف کنم
![image](https://user-images.githubusercontent.com/24356465/87187780-f79f8900-c302-11ea-9027-1253c99aedb1.png)
![image](https://user-images.githubusercontent.com/24356465/87187809-0423e180-c303-11ea-80e5-9f3240c486b6.png)

**Comment by Hamedkalantari0111** [comment]
در واقع وقتی دکمه ویرایش را میزنم، اطلاعات ثبت شده را نمایش نمی دهد!

**Comment by Hamedkalantari0111** [comment]
متاسفانه الان دارم چک میکنم، مشکل ویرایش برای همه رکوردهای ثبت شده سرمایه وجود دارد

**Comment by lamso1387** [comment]
برطرف شد
