### ISSUE TITLE
عدم ورود با زدن دکمه اینتر

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#18]
![image](https://user-images.githubusercontent.com/24356465/87222907-47c32d80-c38d-11ea-8072-b403a21a0251.png)

**Comment by Hamedkalantari0111** [comment]
چهههههه؟

**Comment by lamso1387** [comment]
درست شد
توجه: در همه فرم ها اینتر بزنی کار میکنه
همچنین در همه فرم ها اگه اسکیپ بزنی
Esc
کار دکمه انصراف رو میکنه

یه نکته دیگه:  در همه فرم ها سما راست دکمه ذخیره یه ذره فضای خالی داره با موس اونجا کلیک کن نگه دار میتونی پنجره رو جابجا کنی

**Comment by Hamedkalantari0111** [comment]
احسنت
