### ISSUE TITLE
اصلاح فرم داشبورد

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#2]
در داشبورد یک ردیف در انتهای لیست نمایش بیاید و مجموع را نمایش دهد. 
برای برای فیلدهای زیز مجموع نمایش داده شود: 
جمع کل هزینه سرمایه گذاری
جمع کل ارزش فعلی سرمایه
جمع کل سود موزون
جمع کل سود

**Comment by lamso1387** [comment]
اصلاح شد
