### ISSUE TITLE
نیاز به راهنمای تصویری برای بارگذاری فایل اکسل

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#20]
یک راهنمای تصویری برای بارگذاری فایل اکسل به شکل زیر باشد
![image](https://user-images.githubusercontent.com/24356465/87461895-55461500-c624-11ea-847c-19a9eebf853f.png)

بعد یک سوال دیگه. آیا سطر اول اکسل را باید در زمان بارگذاری حذف کنیم یا نیاز نیست و نرم افزار در زمان ثبت از سطر دوم می خواند؟ این رو هم در راهنما زیر تصویر ذکر کن که مثلا نیاز به حذف سطر اول هست یا نیست

**Comment by lamso1387** [comment]
[
![add_unitcost_by_excell](https://user-images.githubusercontent.com/23126723/87624437-04760f80-c73d-11ea-86a3-46a8613aac2b.png)
](url)
