### ISSUE TITLE
حذف فیلتر سرمایه گذاری از بالای داشبورد

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#21]
دستت درد نکنه ایده خوبی بود. ولی اولا این درست کار نمیکنه. و فقط هزینه سرمایه گذری درست کار میکنه، وقتی فیلتر میکنیم!!!!!! این از این
ثانیا به نظر چون داشبورد داره یک سری اطلاعات جامع و کلی در مورد وضعیت سرمایه گذاری میده درست نیست اینجا فیلتر سرمایه گذاری رو ببینیم و اینکه تمام اطلاعات جدول داشبورد را واقعا نمیخواهیم برای سرمایه گذاری. 
بهت میگم چی برای سرمایه گذاری میخواهیم.
فعلا در این تیکت نظرم اینه که حذف بشه از بالای داشبورد
![image](https://user-images.githubusercontent.com/24356465/88183153-568bc900-cc46-11ea-8f07-06cd28faf8c8.png)

**Comment by lamso1387** [comment]
حذف شد
