### ISSUE TITLE
نیاز به ویزارد برای نمایش میزان سرمایه گذاری هر سرمایه گذار

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#22]
لطفا برای این فرم در همان ویزاردی که خالی است این فرم زیر را ایجاد نمائید
فرم a:
![image](https://user-images.githubusercontent.com/24356465/88184655-378e3680-cc48-11ea-8eab-7bff8c17e08c.png)
شکلC:
![image](https://user-images.githubusercontent.com/24356465/88184774-5d1b4000-cc48-11ea-9b96-0361b3c77b8e.png)

**Comment by Hamedkalantari0111** [comment]
![WhatsApp Image 2020-07-22 at 6 19 38 PM](https://user-images.githubusercontent.com/24356465/88184920-8d62de80-cc48-11ea-9166-216e73e01cc5.jpeg)

**Comment by Hamedkalantari0111** [comment]
اطلاعات هر صندوق به صورت زیر باشد. این دقیقا در شیت های اکسل من هست فیلدهاش

![image](https://user-images.githubusercontent.com/24356465/88185032-ac617080-cc48-11ea-982d-61f9b8a749d9.png)

**Comment by Hamedkalantari0111** [comment]
این فرم ها در اینجا بیاید
![image](https://user-images.githubusercontent.com/24356465/88186559-92c12880-cc4a-11ea-800c-5d256c01ca4e.png)

**Comment by lamso1387** [comment]
انجام شد جهت تست
