### ISSUE TITLE
چند فیلدی درصد با دو رقم اعشار شود

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#23]
![image](https://user-images.githubusercontent.com/24356465/88185225-ef234880-cc48-11ea-9c50-d5a1be9d376e.png)

**Comment by lamso1387** [comment]
شد

**Comment by Hamedkalantari0111** [comment]
@lamso1387 
اینجا ستون سهم از سود اشتباه است. فکر کنم در 100 ضرب نکردی
