### ISSUE TITLE
محاسبه سهم از کل اشتباه است

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#24]
باید این باشد
![image](https://user-images.githubusercontent.com/24356465/88185671-77095280-cc49-11ea-901d-b97cab32b042.png)
ستون سهم از کل برابر است با 
ستون (هزینه خرید واحدهای سرمایه گذاری) تقسیم بر 
ستون 
(مجموع هزینه خرید واحد های سرمایه گذاری)

**Comment by lamso1387** [comment]
سلام لطفا در نسجه جدید تست کن

**Comment by Hamedkalantari0111** [comment]
سلام سهم از کل درست شد
