### ISSUE TITLE
خطا در محسابه ستون نسبت سود به مدت سرمایه گذاری

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#25]
ستون
**نسبت سود به مدت سرمایه‌گذاری** 
در داشبورد 
نیز اشتباه محاسبه می شود
اگر بلد نبودی بگو بهم چطور محاسبه میشه چون در فایل اکسل من دقیقا قرار دارد. در هر شیت مربوط به اکسل ستون 
L
جمعش میشود این ستون

**Comment by Hamedkalantari0111** [comment]
![image](https://user-images.githubusercontent.com/24356465/88186239-30682800-cc4a-11ea-9eba-2433f9213288.png)

**Comment by Hamedkalantari0111** [comment]
ستون درست در تاریخ 990431 باید این شود
![image](https://user-images.githubusercontent.com/24356465/88186316-4544bb80-cc4a-11ea-80bf-640e016c15ec.png)

**Comment by Hamedkalantari0111** [comment]
اگر این ستون را درست کنی، ستون بعدی خود به خود درست میشود. ولی لطفا ستون بعدی را به درصد بیار!!!
منظورم ستون زیر است
پیش بینی سود یکسال

**Comment by lamso1387** [comment]
درست شد

**Comment by Hamedkalantari0111** [comment]
@lamso1387 
هنوز اشتباه است. فایل اکسل رو در فولدر مربوط به ا
 ویندوزی قرار دادم چک کن
