### ISSUE TITLE
اصلاح عدد میانگین سود کل سرمایه گذاری در صندوق

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#5]
@lamso1387 
در بخش داشبورد، فیلد میانگین سود کل سرمایه گذار در صندوق تقسیم بر صد نمیشود.  فقط می شود مجموع میانگین در صد سود موزون صندوق
![image](https://user-images.githubusercontent.com/24356465/84363546-26332280-abe4-11ea-84fc-c5339cedf854.png)

**Comment by lamso1387** [comment]
اصلاح شد
