### ISSUE TITLE
 امکان بارگذاری اطلاعات ارزش خالص صندوق ها در اپ

### ISSUE THREAD

**Issue by Hamedkalantari0111** [hsbors/winapp#7]
در اپ یک بخشی وجود داشته باشد که بتوان اطلاعات ان ای وی 
NAV
صندوق را در قالب فایل اکسل در آن بارگذاری کرد. 
نمونه این فایل اکسل به آدرس دراباکس زیر است. 
Dropbox\Bors\Dashboard Sandoogh\Dashboard\لیست قیمت صدور و ابطال صندوق ها\until 990413
گفتنی است وقتی این امکان در نرم افزار باشه. دیگه نیازی نیست هر بار اطلاعات هزینه ابطال ثبت بشه تا ارزش سرمایه بروز را ببنیم.

**Comment by lamso1387** [comment]
انجام شد
